
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author InfoLabA-PC04
 */
public class BrilloGU extends javax.swing.JFrame {
    
    private Imagen image;
    private JFrame vistaPrevia;
    
    private int currentRangeR;
    private int nextRangeR;
    private int currentRangeG;
    private int nextRangeG;
    private int currentRangeB;
    private int nextRangeB;
    
    /**
     * Creates new form BrilloGU
     */
    public BrilloGU() {
        initComponents();
        
        this.currentRangeR = this.sliderVariacionR.getValue();
        this.nextRangeR = this.sliderVariacionR.getValue();
        
        this.currentRangeG = this.sliderVariacionG.getValue();
        this.nextRangeG = this.sliderVariacionG.getValue();
        
        this.currentRangeB = this.sliderVariacionB.getValue();
        this.nextRangeB = this.sliderVariacionB.getValue();
    }

    public Imagen getImage() {
        return image;
    }

    public void setImage(Imagen image) {
        this.image = image;
    }

    public JFrame getVistaPrevia() {
        return vistaPrevia;
    }

    public void setVistaPrevia(JFrame vistaPrevia) {
        this.vistaPrevia = vistaPrevia;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sliderVariacionR = new javax.swing.JSlider();
        btnSave = new javax.swing.JButton();
        sliderVariacionB = new javax.swing.JSlider();
        sliderVariacionG = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        sliderVariacionR.setMaximum(510);
        sliderVariacionR.setValue(255);
        sliderVariacionR.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sliderVariacionRMouseDragged(evt);
            }
        });
        sliderVariacionR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sliderVariacionRMouseReleased(evt);
            }
        });

        btnSave.setText("Guardar");

        sliderVariacionB.setMaximum(510);
        sliderVariacionB.setValue(255);
        sliderVariacionB.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sliderVariacionBMouseDragged(evt);
            }
        });
        sliderVariacionB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sliderVariacionBMouseReleased(evt);
            }
        });

        sliderVariacionG.setMaximum(510);
        sliderVariacionG.setValue(255);
        sliderVariacionG.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sliderVariacionGMouseDragged(evt);
            }
        });

        jLabel1.setText("R");

        jLabel2.setText("G");

        jLabel3.setText("B");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sliderVariacionR, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                            .addComponent(sliderVariacionG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sliderVariacionB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderVariacionR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderVariacionG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderVariacionB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sliderVariacionRMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliderVariacionRMouseReleased
        /*
        this.nextRange = this.sliderVariacionR.getValue();
        System.out.println("Current value: " + this.currentRange);
        System.out.println("New value: " + nextRange);
        
        int variacion = this.nextRange - this.currentRange;
        System.out.println("Variacion: " + variacion);
        this.currentRange = this.nextRange;
        
        // Algoritmo
        this.image.brillo(variacion);
        this.vistaPrevia.repaint();*/
        
    }//GEN-LAST:event_sliderVariacionRMouseReleased

    private void sliderVariacionBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliderVariacionBMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sliderVariacionBMouseReleased

    private void sliderVariacionRMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliderVariacionRMouseDragged
        this.nextRangeR = this.sliderVariacionR.getValue();
        
        int variacion = this.nextRangeR - this.currentRangeR;
        this.currentRangeR = this.nextRangeR;
        
        // Algoritmo
        this.image.brillo(variacion, 'R');
        this.vistaPrevia.repaint();
    }//GEN-LAST:event_sliderVariacionRMouseDragged

    private void sliderVariacionGMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliderVariacionGMouseDragged
        this.nextRangeG = this.sliderVariacionG.getValue();
        
        int variacion = this.nextRangeG - this.currentRangeG;
        this.currentRangeG = this.nextRangeG;
        
        // Algoritmo
        this.image.brillo(variacion, 'G');
        this.vistaPrevia.repaint();
    }//GEN-LAST:event_sliderVariacionGMouseDragged

    private void sliderVariacionBMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliderVariacionBMouseDragged
        this.nextRangeB = this.sliderVariacionB.getValue();
        
        int variacion = this.nextRangeB - this.currentRangeB;
        this.currentRangeB = this.nextRangeB;
        
        // Algoritmo
        this.image.brillo(variacion, 'B');
        this.vistaPrevia.repaint();
    }//GEN-LAST:event_sliderVariacionBMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrilloGU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrilloGU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrilloGU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrilloGU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BrilloGU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSlider sliderVariacionB;
    private javax.swing.JSlider sliderVariacionG;
    private javax.swing.JSlider sliderVariacionR;
    // End of variables declaration//GEN-END:variables
}
